name: Docker Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ github.event_name == 'push' && github.ref != 'refs/tags/' && github.ref != 'refs/heads/main' && github.ref || 'latest' }}

    - name: Release Docker image
      if: github.event_name == 'push' && github.ref == 'refs/tags/*'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ github.ref }}
    - name: Archive cv.html
      uses: actions/upload-artifact@v2
      with:
        name: cv-artifact
        path: /opt/app/cv.html

